### PR TITLE
Fix the typo on the Prune error message #18

### LINKED ISSUE #18: Fix the typo on the Prune error message

### PR DESCRIPTION
**Pull request by BosEriko**
# Story Title

[Fix the typo on the Prune error message](https://github.com/kuru-project/discord-bot/issues/18)

# Changes made

- Fix the typo
- Capitalize the sentences on Prune

# How does the solution address the problem

This PR will fix the Typo and the Prune command.

# Linked issues

Resolves #18

### CODE REVIEW

File: src/commands/prune.ts [hunk 1]
```diff
@@ -3,21 +3,21 @@ module.exports = {
   description: 'Prune Messages',
   execute(message, args, adminID) {
     if (message.author.id !== adminID) {
-      return message.reply('You\' not an powerfule enough!');
+      return message.reply('You\'re not an powerful enough!');
```
Comment (NeonNature) [inline src/commands/prune.ts:6]: Would it be better if "You're not powerful enough"?

Comment (BosEriko) [reply src/commands/prune.ts:6]: fixed
